version: 1
formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s: %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file:
        class : logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple 
        filename: log/logfile.log
        maxBytes: 50000
        backupCount: 3
loggers:
    __main__:
        level: DEBUG
        handlers: [file]
        propagate: no

root:
    level: DEBUG
    handlers: [console]